const WaifuBanq = [
    {
      name: "Sakura Haruno",
      type: "Chakra",
      count: 56,
      imgSrc: "lien_vers_image_1.png",
      changeCount: 0,
    },
    {
      name: "Asuna Yuuki",
      type: "Mana",
      count: 23,
      imgSrc: "lien_vers_image_2.png",
      changeCount: 0,
    },
    {
      name: "Kagome Higurashi",
      type: "Ki",
      count: 78,
      imgSrc: "lien_vers_image_3.png",
      changeCount: 0,
    },
    {
      name: "Rias Gremory",
      type: "Énergie Spirituelle",
      count: 12,
      imgSrc: "lien_vers_image_4.png",
      changeCount: 0,
    },
    {
      name: "Mikasa Ackerman",
      type: "Mana",
      count: 45,
      imgSrc: "lien_vers_image_5.png",
      changeCount: 0,
    },
    {
      name: "Rei Ayanami",
      type: "Chakra",
      count: 89,
      imgSrc: "lien_vers_image_6.png",
      changeCount: 0,
    },
    {
      name: "Lum Invader",
      type: "Ki",
      count: 34,
      imgSrc: "lien_vers_image_7.png",
      changeCount: 0,
    },
    {
      name: "Holo the Wise Wolf",
      type: "Énergie Spirituelle",
      count: 67,
      imgSrc: "lien_vers_image_8.png",
      changeCount: 0,
    },
    {
      name: "Zero Two",
      type: "Chakra",
      count: 56,
      imgSrc: "lien_vers_image_9.png",
      changeCount: 0,
    },
    {
      name: "Nico Robin",
      type: "Mana",
      count: 234,
      imgSrc: "lien_vers_image_10.png",
      changeCount: 0,
    },
    {
      name: "Inori Yuzuriha",
      type: "Ki",
      count: 789,
      imgSrc: "lien_vers_image_11.png",
      changeCount: 0,
    },
    {
      name: "Matoi Ryuko",
      type: "Énergie Spirituelle",
      count: 123,
      imgSrc: "lien_vers_image_12.png",
      changeCount: 0,
    },
    {
      name: "Nami",
      type: "Mana",
      count: 456,
      imgSrc: "lien_vers_image_13.png",
      changeCount: 0,
    },
    {
      name: "Sailor Moon",
      type: "Chakra",
      count: 890,
      imgSrc: "lien_vers_image_14.png",
      changeCount: 0,
    },
    {
      name: "Yuno Gasai",
      type: "Ki",
      count: 345,
      imgSrc: "lien_vers_image_15.png",
      changeCount: 0,
    },
    {
      name: "Motoko Kusanagi",
      type: "Énergie Spirituelle",
      count: 678,
      imgSrc: "lien_vers_image_16.png",
      changeCount: 0,
    },
    {
      name: "Lucy Heartfilia",
      type: "Chakra",
      count: 567,
      imgSrc: "lien_vers_image_17.png",
      changeCount: 0,
    },
    {
      name: "Akeno Himejima",
      type: "Mana",
      count: 234,
      imgSrc: "lien_vers_image_18.png",
      changeCount: 0,
    },
    {
      name: "Satsuki Kiryuin",
      type: "Ki",
      count: 789,
      imgSrc: "lien_vers_image_19.png",
      changeCount: 0,
    },
    {
      name: "Misa Amane",
      type: "Énergie Spirituelle",
      count: 123,
      imgSrc: "lien_vers_image_20.png",
      changeCount: 0,
    },
  ];
  
  export default WaifuBanq;