const WaifuBanq = [
  {
    name: "Sakura Haruno",
    type: "Chakra",
    count: 56,
    imgSrc: "https://cdn.waifu.im/5533.jpg",
    changeCount: 0,
  },
  {
    name: "Asuna Yuuki",
    type: "Mana",
    count: 23,
    imgSrc: "https://cdn.waifu.im/6621.jpeg",
    changeCount: 0,
  },
  {
    name: "Kagome Higurashi",
    type: "Ki",
    count: 78,
    imgSrc: "https://cdn.waifu.im/6605.jpeg",
    changeCount: 0,
  },
  {
    name: "Rias Gremory",
    type: "Énergie Spirituelle",
    count: 12,
    imgSrc: "https://cdn.waifu.im/6784.jpg",
    changeCount: 0,
  },
  {
    name: "Mikasa Ackerman",
    type: "Mana",
    count: 45,
    imgSrc: "https://cdn.waifu.im/6620.jpeg",
    changeCount: 0,
  },
  {
    name: "Rei Ayanami",
    type: "Chakra",
    count: 89,
    imgSrc: "https://cdn.waifu.im/6530.jpeg",
    changeCount: 0,
  },
  {
    name: "Lum Invader",
    type: "Ki",
    count: 34,
    imgSrc: "https://cdn.waifu.im/6650.jpeg",
    changeCount: 0,
  },
  {
    name: "Holo the Wise Wolf",
    type: "Énergie Spirituelle",
    count: 67,
    imgSrc: "https://cdn.waifu.im/4715.jpeg",
    changeCount: 0,
  },
  {
    name: "Zero Two",
    type: "Chakra",
    count: 56,
    imgSrc: "https://cdn.waifu.im/3423.jpg",
    changeCount: 0,
  },
  {
    name: "Nico Robin",
    type: "Mana",
    count: 234,
    imgSrc: "https://cdn.waifu.im/6646.jpg",
    changeCount: 0,
  },
  {
    name: "Inori Yuzuriha",
    type: "Ki",
    count: 789,
    imgSrc: "https://cdn.waifu.im/6784.jpg",
    changeCount: 0,
  },
  {
    name: "Matoi Ryuko",
    type: "Énergie Spirituelle",
    count: 123,
    imgSrc: "https://cdn.waifu.im/7701.jpg",
    changeCount: 0,
  },
  {
    name: "Nami",
    type: "Mana",
    count: 456,
    imgSrc: "https://cdn.waifu.im/6605.jpeg",
    changeCount: 0,
  },
  {
    name: "Sailor Moon",
    type: "Chakra",
    count: 890,
    imgSrc: "https://cdn.waifu.im/7701.jpg",
    changeCount: 0,
  },
  {
    name: "Yuno Gasai",
    type: "Ki",
    count: 345,
    imgSrc: "https://cdn.waifu.im/6621.jpeg",
    changeCount: 0,
  },
  {
    name: "Motoko Kusanagi",
    type: "Énergie Spirituelle",
    count: 678,
    imgSrc: "https://cdn.waifu.im/6617.jpeg",
    changeCount: 0,
  },
  {
    name: "Lucy Heartfilia",
    type: "Chakra",
    count: 567,
    imgSrc: "https://cdn.waifu.im/7386.jpg",
    changeCount: 0,
  },
  {
    name: "Akeno Himejima",
    type: "Mana",
    count: 235,
    imgSrc: "https://cdn.waifu.im/7347.jpg",
    changeCount: 0,
  },
  {
    name: "Satsuki Kiryuin",
    type: "Ki",
    count: 789,
    imgSrc: "https://cdn.waifu.im/6641.jpeg",
    changeCount: 0,
  },
  {
    name: "Misa Amane",
    type: "Énergie Spirituelle",
    count: 123,
    imgSrc: "https://cdn.waifu.im/6659.jpeg",
    changeCount: 0,
  },
];

export default WaifuBanq;
